# Generated by Django 3.0.1 on 2020-01-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('roomtype', models.CharField(max_length=20)),
                ('roomno', models.IntegerField()),
                ('cemail', models.EmailField(max_length=254)),
                ('ccontact', models.CharField(max_length=15)),
                ('cfile', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_image', models.URLField()),
                ('destination_name', models.CharField(max_length=50)),
                ('destination_description', models.CharField(max_length=70)),
            ],
        ),
    ]
