# Generated by Django 3.0.1 on 2020-02-10 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('roomtype', models.CharField(max_length=20)),
                ('roomno', models.IntegerField()),
                ('cemail', models.EmailField(max_length=254)),
                ('ccontact', models.CharField(max_length=15)),
                ('cfile', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_image', models.URLField()),
                ('hotel_name', models.CharField(max_length=50)),
                ('hotel_description', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('TelephoneNumber', models.CharField(max_length=12)),
                ('ImagePath', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('Description', models.TextField(max_length=140)),
            ],
            options={
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomType', models.CharField(max_length=255)),
                ('Capacity', models.IntegerField(default=0)),
                ('BedOption', models.CharField(max_length=255)),
                ('Price', models.IntegerField(default=0)),
                ('View', models.CharField(max_length=255)),
                ('TotalRooms', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Hotels')),
            ],
            options={
                'verbose_name_plural': 'Room',
            },
        ),
    ]
