# Generated by Django 3.0.1 on 2020-01-28 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Hotel_Image',
        ),
        migrations.RenameField(
            model_name='hotel_image',
            old_name='destination_description',
            new_name='hotel_description',
        ),
        migrations.RenameField(
            model_name='hotel_image',
            old_name='destination_image',
            new_name='hotel_image',
        ),
        migrations.RenameField(
            model_name='hotel_image',
            old_name='destination_name',
            new_name='hotel_name',
        ),
    ]
